services:
  mysql:
    image: mysql:8.0
    container_name: riskhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: riskhub123
      MYSQL_DATABASE: riskhub
      MYSQL_USER: riskhub
      MYSQL_PASSWORD: riskhub123
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - riskhub-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: riskhub-redis
    ports:
      - "6379:6379"
    volumes:
      - riskhub-redis-data:/data

  namesrv:
    image: apache/rocketmq:5.1.3
    container_name: riskhub-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"

  broker:
    image: apache/rocketmq:5.1.3
    container_name: riskhub-broker
    ports:
      - "10911:10911"
      - "10909:10909"
    depends_on:
      - namesrv
    command: sh mqbroker -n namesrv:9876 --enable-proxy
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"
      NAMESRV_ADDR: "namesrv:9876"

volumes:
  riskhub-mysql-data:
  riskhub-redis-data:
